### ISSUE TITLE
Add volume control

### ISSUE THREAD

**Issue by bucchere** [labzero/hedwig_mopidy#5]
+1 "unit" and -1 "unit" only

**Comment by bucchere** [comment]
Add a "mopidy spot" for where the volume should be

**Comment by bucchere** [comment]
I tapefied the amp.

**Comment by holetse** [comment]
I'm really amped for this PR.

**Comment by bucchere** [comment]
We'll make sure nothing causes any impedance.

**Comment by bucchere** [comment]
`dj volume` replies with the current volume level (0-10)
`dj volume up|more|moar|+|++|+1` increases the volume by 1 level
`dj volume down|less|-|--|-1` decreases the volume by 1 level
`dj crank it` increases the volume by 3 levels
